# Generated by Django 5.0.6 on 2026-06-24 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='mensajes/')),
                ('segmento', models.CharField(choices=[('recinto', 'Recinto'), ('zona', 'Zona'), ('evento', 'Evento'), ('todos_eventos', 'Todos los eventos'), ('todos_recintos', 'Todos los recintos'), ('recintos_y_zonas', 'Recintos y zonas')], default='recinto', max_length=20)),
                ('segmento_id', models.BigIntegerField(blank=True, null=True)),
                ('estado', models.IntegerField(choices=[(0, 'Pendiente'), (1, 'En progreso'), (2, 'Cancelado'), (3, 'Completado')], default=0)),
                ('progreso', models.FloatField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DestinatarioMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('fallido', 'Fallido')], db_index=True, default='pendiente', max_length=10)),
                ('external_id', models.CharField(blank=True, max_length=64, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='mensajeria.mensaje')),
            ],
        ),
    ]
