# Generated by Django 5.0.6 on 2026-07-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mensajeria", "0002_destinatariomensaje_actualizado_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroEnvio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("destino_mascara", models.CharField(max_length=24)),
                ("proveedor", models.CharField(max_length=20)),
                ("ok", models.BooleanField(default=False)),
                ("external_id", models.CharField(blank=True, max_length=64, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("creado", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-creado"],
            },
        ),
        migrations.AddField(
            model_name="destinatariomensaje",
            name="proveedor",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
