# Generated by Django 5.0.6 on 2026-07-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mensajeria", "0003_registroenvio_destinatariomensaje_proveedor"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreferenciaMensajeria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("proveedores_orden", models.JSONField(blank=True, default=list)),
                ("failover_habilitado", models.BooleanField(default=True)),
                ("reintentos", models.PositiveSmallIntegerField(default=1)),
                ("timeout_ms", models.PositiveIntegerField(default=15000)),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Preferencia de mensajería",
            },
        ),
    ]
