# Generated by Django 5.0.6 on 2026-07-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mensajeria", "0004_preferenciamensajeria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destinatariomensaje",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("enviado", "Enviado"),
                    ("entregado", "Entregado"),
                    ("leido", "Leído"),
                    ("fallido", "Fallido"),
                ],
                db_index=True,
                default="pendiente",
                max_length=10,
            ),
        ),
    ]
