# Generated by Django 5.0.6 on 2026-07-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mensajeria", "0005_alter_destinatariomensaje_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="preferenciamensajeria",
            name="connection_id",
            field=models.CharField(default="principal", max_length=64),
        ),
    ]
