# Generated by Django 5.0.6 on 2026-06-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sancion',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
