# Generated by Django 5.0.6 on 2026-06-24 21:52

import common.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('empleados', '0001_initial'),
        ('proveedores', '0003_proveedor_cuentaproveedor_proveedor'),
        ('recintos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('limite', models.IntegerField(blank=True, null=True)),
                ('tipo', models.IntegerField(choices=[(0, 'Proveedor'), (1, 'Directa')], default=0)),
                ('tipo_cita', models.CharField(choices=[('programada', 'Programada'), ('walk_in', 'Walk-in'), ('emergencia', 'Emergencia')], default='programada', max_length=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=12)),
                ('acceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recintos.acceso')),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas_creadas', to=settings.AUTH_USER_MODEL)),
                ('protocolo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recintos.protocolo')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedores.proveedor')),
                ('punto_acceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_punto_acceso', to='recintos.ubicacion')),
                ('recinto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recintos.recinto')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_ubicacion', to='recintos.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='AsistenteCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('estado', models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Confirmado'), (2, 'Cancelado')], default=0)),
                ('tipo', models.IntegerField(choices=[(0, 'Contacto'), (1, 'Empleado')], default=0)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('requiere_ine', models.BooleanField(default=True)),
                ('ine_capturado', models.BooleanField(default=False)),
                ('ine_data', common.fields.EncryptedJSONField(blank=True, null=True)),
                ('path_ine', models.FileField(blank=True, null=True, upload_to='citas/ine/')),
                ('tipo_identificacion', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('numero_identificacion', common.fields.EncryptedCharField(blank=True, null=True)),
                ('estado_adicional', models.PositiveSmallIntegerField(default=0)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistentes', to='citas.cita')),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.cita')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
            ],
            options={
                'unique_together': {('empleado', 'cita')},
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='empleados',
            field=models.ManyToManyField(through='citas.EmpleadoCita', to='empleados.empleado'),
        ),
    ]
