# Generated by Django 5.0.6 on 2026-06-24 21:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
        ('empleados', '0001_initial'),
        ('eventos', '0001_initial'),
        ('proveedores', '0003_proveedor_cuentaproveedor_proveedor'),
        ('recintos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpleadoEventoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusdocs', models.IntegerField(choices=[(0, 'Docs pendientes'), (1, 'Cumple')], default=0)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='EventoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite', models.IntegerField(default=0)),
                ('requiere_parking', models.BooleanField(default=False)),
                ('cajones_parking', models.IntegerField(default=0)),
                ('notas', models.TextField(blank=True, null=True)),
                ('acceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recintos.acceso')),
                ('empleados', models.ManyToManyField(through='eventos.EmpleadoEventoProveedor', to='empleados.empleado')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='eventos.evento')),
                ('protocolo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recintos.protocolo')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
                ('punto_acceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='es_punto_acceso', to='recintos.ubicacion')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='es_ubicacion', to='recintos.ubicacion')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recintos.zona')),
            ],
            options={
                'unique_together': {('evento', 'proveedor')},
            },
        ),
        migrations.AddField(
            model_name='empleadoeventoproveedor',
            name='evento_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='eventos.eventoproveedor'),
        ),
        migrations.CreateModel(
            name='CajonParking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('evento_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajones', to='eventos.eventoproveedor')),
            ],
        ),
        migrations.CreateModel(
            name='EventoGrupoDocumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_validation', models.IntegerField(choices=[(0, 'Al menos uno'), (1, 'Todos')], default=0)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_documentos', to='eventos.evento')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.grupodocumentos')),
            ],
            options={
                'unique_together': {('evento', 'grupo')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='empleadoeventoproveedor',
            unique_together={('empleado', 'evento_proveedor')},
        ),
        migrations.CreateModel(
            name='EventoTipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_documento', to='eventos.evento')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.tipodocumento')),
            ],
            options={
                'unique_together': {('evento', 'tipo_documento')},
            },
        ),
    ]
