# Generated by Django 5.0.6 on 2026-06-25 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventos", "0002_empleadoeventoproveedor_eventoproveedor_and_more"),
        ("recintos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaAutorizadaEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recintos.areaautorizada"
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="eventos.evento"
                    ),
                ),
            ],
            options={
                "unique_together": {("area", "evento")},
            },
        ),
        migrations.AddField(
            model_name="evento",
            name="areas_autorizadas",
            field=models.ManyToManyField(
                related_name="eventos",
                through="eventos.AreaAutorizadaEvento",
                to="recintos.areaautorizada",
            ),
        ),
        migrations.CreateModel(
            name="AreaAutorizadaEventoProveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recintos.areaautorizada"
                    ),
                ),
                (
                    "evento_proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="eventos.eventoproveedor"
                    ),
                ),
            ],
            options={
                "unique_together": {("area", "evento_proveedor")},
            },
        ),
        migrations.AddField(
            model_name="eventoproveedor",
            name="areas_autorizadas",
            field=models.ManyToManyField(
                related_name="eventos_proveedor",
                through="eventos.AreaAutorizadaEventoProveedor",
                to="recintos.areaautorizada",
            ),
        ),
    ]
