# Generated by Django 5.0.6 on 2026-06-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_cajonparking_actualizado_cajonparking_creado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoproveedor',
            name='parking',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
