# Generated by Django 5.0.6 on 2026-06-24 20:10

from django.db import migrations, models

import apps.proveedores.models
import common.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CuentaProveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                ("nombre", models.CharField(max_length=160)),
                ("apellidos", models.CharField(blank=True, max_length=160, null=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("email_verificado", models.DateTimeField(blank=True, null=True)),
                (
                    "rol",
                    models.CharField(
                        choices=[("admin", "Admin"), ("usuario", "Usuario")],
                        default="usuario",
                        max_length=10,
                    ),
                ),
                ("puesto", models.CharField(blank=True, max_length=120, null=True)),
                ("telefono", models.CharField(blank=True, max_length=30, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("curp", common.fields.EncryptedCharField(blank=True, null=True)),
                ("nss", common.fields.EncryptedCharField(blank=True, null=True)),
                ("file_ine", models.FileField(blank=True, null=True, upload_to="proveedores/ine/")),
                ("foto", models.ImageField(blank=True, null=True, upload_to="proveedores/fotos/")),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", apps.proveedores.models.CuentaProveedorManager()),
            ],
        ),
    ]
