# Generated by Django 5.0.6 on 2026-06-24 20:43

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaproveedor',
            name='mfa_habilitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cuentaproveedor',
            name='mfa_totp_secret',
            field=common.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
