# Generated by Django 5.0.6 on 2026-06-24 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_usuario_mfa_habilitado_usuario_mfa_totp_secret"),
        ("recintos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="recinto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios",
                to="recintos.recinto",
            ),
        ),
    ]
