# Generated by Django 5.0.6 on 2026-07-08 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_permisousuario"),
    ]

    operations = [
        migrations.CreateModel(
            name="CredencialWebAuthn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("credential_id", models.CharField(db_index=True, max_length=255, unique=True)),
                ("public_key", models.TextField()),
                ("sign_count", models.PositiveBigIntegerField(default=0)),
                ("transports", models.CharField(blank=True, max_length=120, null=True)),
                ("nombre", models.CharField(default="Llave de seguridad", max_length=80)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credenciales_webauthn",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-creado"],
                "abstract": False,
            },
        ),
    ]
