# Generated by Django 5.0.6 on 2026-06-24 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("proveedores", "0003_proveedor_cuentaproveedor_proveedor"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultaLista69b",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tipo", models.IntegerField(default=0)),
                ("creado", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SatEfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("rfc", models.CharField(db_index=True, max_length=13, unique=True)),
                ("nombre", models.CharField(blank=True, max_length=255, null=True)),
                ("situacion", models.CharField(max_length=40)),
                ("meta", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ResultadoLista69b",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("rfc", models.CharField(blank=True, max_length=13, null=True)),
                ("query_data", models.JSONField(blank=True, null=True)),
                (
                    "estado",
                    models.IntegerField(choices=[(0, "Limpio"), (1, "Encontrado")], default=0),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "consulta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados",
                        to="cumplimiento.consultalista69b",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="proveedores.proveedor"
                    ),
                ),
            ],
        ),
    ]
