# Generated by Django 5.0.6 on 2026-07-03 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cumplimiento", "0002_resultadolista69b_actualizado_satefo_actualizado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="satefo",
            name="nombre",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="satefo",
            name="situacion",
            field=models.CharField(max_length=60),
        ),
    ]
