# Generated by Django 5.0.6 on 2026-07-03 00:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cumplimiento", "0003_alter_satefo_nombre_alter_satefo_situacion"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SatEfo",
        ),
    ]
