# Generated by Django 5.0.6 on 2026-07-08 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cumplimiento", "0004_delete_satefo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentoLegal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("aviso_privacidad", "Aviso de Privacidad"),
                            ("terminos_condiciones", "Términos y Condiciones"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                ("texto", models.TextField()),
                ("version", models.PositiveIntegerField(default=1)),
                ("vigente_desde", models.DateTimeField(auto_now_add=True)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
                "indexes": [
                    models.Index(fields=["tipo", "-version"], name="cumplimient_tipo_f77eee_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="SolicitudArco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("acceso", "Acceso"),
                            ("rectificacion", "Rectificación"),
                            ("cancelacion", "Cancelación"),
                            ("oposicion", "Oposición"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "titular_tipo",
                    models.CharField(
                        choices=[
                            ("empleado", "Empleado"),
                            ("cuenta_proveedor", "Cuenta de proveedor"),
                            ("asistente", "Asistente de cita"),
                        ],
                        max_length=20,
                    ),
                ),
                ("titular_id", models.BigIntegerField()),
                ("titular_desc", models.CharField(max_length=120)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("recibida", "Recibida"),
                            ("en_proceso", "En proceso"),
                            ("completada", "Completada"),
                            ("rechazada", "Rechazada"),
                        ],
                        default="recibida",
                        max_length=12,
                    ),
                ),
                ("motivo", models.TextField(blank=True, null=True)),
                ("plazo_limite", models.DateField()),
                ("resuelto", models.DateTimeField(blank=True, null=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "solicitado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-creado"],
                "indexes": [
                    models.Index(
                        fields=["titular_tipo", "titular_id"], name="cumplimient_titular_1bf3a8_idx"
                    )
                ],
            },
        ),
    ]
