# Generated by Django 5.0.6 on 2026-07-14 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0002_opcion_actualizado_opcion_creado"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BitacoraAcceso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "evento",
                    models.CharField(
                        choices=[
                            ("login", "Inicio de sesión"),
                            ("login_fallido", "Intento fallido"),
                            ("logout", "Cierre de sesión"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "contexto",
                    models.CharField(
                        choices=[("acceso", "Operación"), ("proveedores", "Proveedores")],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                ("actor_email", models.CharField(db_index=True, max_length=254)),
                ("actor_nombre", models.CharField(blank=True, default="", max_length=180)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("dispositivo", models.CharField(blank=True, default="", max_length=180)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("exito", models.BooleanField(default=True)),
                ("detalle", models.CharField(blank=True, default="", max_length=200)),
                ("creado", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-creado"],
                "indexes": [
                    models.Index(
                        fields=["contexto", "evento"], name="config_bita_context_33df7d_idx"
                    ),
                    models.Index(
                        fields=["actor_email", "creado"], name="config_bita_actor_e_b0d748_idx"
                    ),
                ],
            },
        ),
    ]
