# Generated by Django 5.0.6 on 2026-07-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0003_bitacoraacceso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historialcambio",
            name="creado",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
