# Generated by Django 5.0.6 on 2026-06-24 19:49

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models

import apps.tenants.models
import common.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DispositivoEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("mac_address", models.CharField(max_length=32, unique=True)),
                ("nombre", models.CharField(max_length=120)),
                ("token", common.fields.EncryptedCharField()),
                ("precinct_id", models.BigIntegerField(blank=True, null=True)),
                ("access_point_id", models.BigIntegerField(blank=True, null=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("clave", models.CharField(max_length=60, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("precio_mensual", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("stripe_price_id", models.CharField(blank=True, max_length=64, null=True)),
                ("modulos", models.JSONField(blank=True, default=list)),
                ("limites", models.JSONField(blank=True, default=dict)),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="SuperAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                ("nombre", models.CharField(max_length=160)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("activo", models.BooleanField(default=True)),
                ("mfa_habilitado", models.BooleanField(default=False)),
                ("mfa_totp_secret", common.fields.EncryptedCharField(blank=True, null=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", apps.tenants.models.SuperAdminManager()),
            ],
        ),
        migrations.CreateModel(
            name="VentanaMantenimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("inicio", models.DateTimeField()),
                ("fin", models.DateTimeField()),
                ("mensaje", models.CharField(blank=True, max_length=255, null=True)),
                ("activa", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("componente", models.CharField(max_length=60)),
                ("numero", models.CharField(max_length=40)),
                ("notas", models.TextField(blank=True, null=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ComandoEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("relay.open", "Abrir relé"), ("display.text", "Mostrar texto")],
                        max_length=50,
                    ),
                ),
                ("port", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("texto", models.CharField(blank=True, max_length=255, null=True)),
                ("timeout_sec", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("sent", "Enviado"),
                            ("ack", "Confirmado"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("nonce", models.CharField(blank=True, max_length=64, null=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "dispositivo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comandos",
                        to="tenants.dispositivoedge",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[django_tenants.postgresql_backend.base._check_schema_name],
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("activo", "Activo"),
                            ("suspendido", "Suspendido"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="trial",
                        max_length=12,
                    ),
                ),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                ("modo_solo_lectura", models.BooleanField(default=False)),
                ("stripe_customer_id", models.CharField(blank=True, max_length=64, null=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_on", models.DateField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tenants",
                        to="tenants.plan",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Suscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("activa", "Activa"),
                            ("morosa", "Morosa"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="trial",
                        max_length=12,
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("periodo_inicio", models.DateTimeField(blank=True, null=True)),
                ("periodo_fin", models.DateTimeField(blank=True, null=True)),
                ("cancelar_al_fin_periodo", models.BooleanField(default=False)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="suscripciones",
                        to="tenants.plan",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suscripciones",
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaldoCreditos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("saldo", models.IntegerField(default=0)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saldo_creditos",
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MovimientoCredito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("delta", models.IntegerField()),
                ("motivo", models.CharField(max_length=160)),
                ("saldo_resultante", models.IntegerField()),
                ("referencia", models.CharField(blank=True, max_length=120, null=True)),
                ("creado", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos_credito",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-creado"],
            },
        ),
        migrations.CreateModel(
            name="IntentoPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("moneda", models.CharField(default="MXN", max_length=3)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("exitoso", "Exitoso"),
                            ("fallido", "Fallido"),
                        ],
                        default="pendiente",
                        max_length=10,
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intentos_pago",
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "stripe_invoice_id",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("periodo_inicio", models.DateField(blank=True, null=True)),
                ("periodo_fin", models.DateField(blank=True, null=True)),
                ("url_pdf", models.URLField(blank=True, null=True)),
                ("pagada", models.BooleanField(default=False)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facturas",
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("domain", models.CharField(db_index=True, max_length=253, unique=True)),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="dispositivoedge",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dispositivos",
                to="tenants.tenant",
            ),
        ),
        migrations.CreateModel(
            name="ConfiguracionMesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("base_url", models.URLField(blank=True, null=True)),
                ("api_key", common.fields.EncryptedCharField(blank=True, null=True)),
                ("habilitada", models.BooleanField(default=False)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_mesa",
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
    ]
