# Generated by Django 5.0.6 on 2026-07-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='gracia_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
