# Generated by Django 5.0.6 on 2026-07-03 19:28

from django.db import migrations, models

import common.fields


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0002_tenant_gracia_hasta"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionConnector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("habilitado", models.BooleanField(default=False)),
                ("url_base", models.URLField(blank=True, null=True)),
                ("hmac_secret", common.fields.EncryptedCharField(blank=True, null=True)),
                ("timeout_ms", models.PositiveIntegerField(default=8000)),
                ("intervalo_health", models.PositiveIntegerField(default=30)),
                ("reintentos_default", models.PositiveSmallIntegerField(default=1)),
                (
                    "estrategia_failover",
                    models.CharField(
                        choices=[("secuencial", "Secuencial (failover en orden)")],
                        default="secuencial",
                        max_length=20,
                    ),
                ),
                ("cb_umbral", models.PositiveSmallIntegerField(default=5)),
                ("cb_cooldown", models.PositiveIntegerField(default=60)),
                ("cb_ventana", models.PositiveIntegerField(default=300)),
                ("recuperacion_automatica", models.BooleanField(default=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración del Connector",
            },
        ),
    ]
