# Generated by Django 5.0.6 on 2026-07-21 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0004_credencialwebauthnadmin"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodigoRespaldoAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("codigo_hash", models.CharField(max_length=255)),
                ("usado_en", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "superadmin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codigos_respaldo",
                        to="tenants.superadmin",
                    ),
                ),
            ],
            options={
                "ordering": ["creado"],
                "abstract": False,
            },
        ),
    ]
