# Generated by Django 5.0.6 on 2026-07-21 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0005_codigorespaldoadmin"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="es_panel_proveedores",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="DirectorioProveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("cuenta_id", models.PositiveIntegerField()),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("activo", models.BooleanField(default=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="directorio_proveedores",
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="directorioproveedor",
            constraint=models.UniqueConstraint(
                fields=("tenant", "cuenta_id"), name="uniq_directorio_tenant_cuenta"
            ),
        ),
    ]
