# Generated by Django 5.0.6 on 2026-06-24 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Acceso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("telefono", models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Protocolo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("archivo", models.FileField(blank=True, null=True, upload_to="protocolos/")),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Recinto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=200, null=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("telefono", models.CharField(blank=True, max_length=30, null=True)),
                ("codigo", models.CharField(blank=True, max_length=60, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Entrada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "acceso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entradas",
                        to="recintos.acceso",
                    ),
                ),
                (
                    "padre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hijas",
                        to="recintos.entrada",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="acceso",
            name="recinto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accesos",
                to="recintos.recinto",
            ),
        ),
        migrations.CreateModel(
            name="Zona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("telefono", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "recinto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zonas",
                        to="recintos.recinto",
                    ),
                ),
            ],
            options={
                "unique_together": {("recinto", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="Ubicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "padre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hijas",
                        to="recintos.ubicacion",
                    ),
                ),
                (
                    "zona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ubicaciones",
                        to="recintos.zona",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AreaAutorizada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "recinto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas",
                        to="recintos.recinto",
                    ),
                ),
            ],
            options={
                "unique_together": {("recinto", "nombre")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="acceso",
            unique_together={("recinto", "nombre")},
        ),
    ]
